type MockCommunicationSeed = {
  type: string;
  direction: string;
  fromAddress: string;
  toAddress: string;
  subject: string | null;
  body: string;
  voicemailUrl: string | null;
  voicemailTranscription: string | null;
  attachments: Array<{ filename: string; url: string; size: number }>;
  isRead: boolean;
  isFlagged: boolean;
  actionNeeded: boolean;
  actionNotes: string | null;
  receivedAt: Date;
};

export const mockCommunicationsSeedData: MockCommunicationSeed[] = [
  // --- Moneris Communications ---
  {
    type: "email",
    direction: "inbound",
    fromAddress: "applications@moneris.com",
    toAddress: "info@maplecommerce.ca",
    subject: "Application Received - Merchant Services",
    body: "Dear Applicant,\n\nThank you for submitting your merchant services application to Moneris Solutions. Your application reference number is MON-2026-04891.\n\nOur underwriting team will review your submission and you can expect to hear from us within 5-10 business days. If we require any additional documentation, we will contact you at this email address.\n\nPlease do not submit a duplicate application.\n\nSincerely,\nMoneris Merchant Onboarding Team",
    voicemailUrl: null,
    voicemailTranscription: null,
    attachments: [],
    isRead: true,
    isFlagged: false,
    actionNeeded: false,
    actionNotes: null,
    receivedAt: new Date("2026-03-15T09:30:00"),
  },
  {
    type: "email",
    direction: "inbound",
    fromAddress: "underwriting@moneris.com",
    toAddress: "info@maplecommerce.ca",
    subject: "Additional Documents Required - MON-2026-04891",
    body: "Dear Merchant,\n\nWe are processing your application MON-2026-04891 and require the following additional documents:\n\n1. Most recent 3 months of business bank statements\n2. A clear copy of your provincial business license\n3. Proof of business address (utility bill or lease agreement)\n\nPlease upload these documents through our secure portal within 10 business days. Failure to provide the requested documentation may result in delays or the closure of your application.\n\nIf you have questions, please contact your assigned underwriter.\n\nRegards,\nMoneris Underwriting Department",
    voicemailUrl: null,
    voicemailTranscription: null,
    attachments: [],
    isRead: true,
    isFlagged: true,
    actionNeeded: true,
    actionNotes: "Need to upload bank statements and business license. Deadline: 10 business days.",
    receivedAt: new Date("2026-03-20T14:15:00"),
  },
  {
    type: "sms",
    direction: "inbound",
    fromAddress: "+18002637626",
    toAddress: "+14162831047",
    subject: null,
    body: "Moneris: Your verification code is 847293. This code expires in 10 minutes. Do not share this code with anyone. Ref: MON-2026-04891",
    voicemailUrl: null,
    voicemailTranscription: null,
    attachments: [],
    isRead: true,
    isFlagged: false,
    actionNeeded: false,
    actionNotes: null,
    receivedAt: new Date("2026-03-22T10:05:00"),
  },
  {
    type: "call",
    direction: "inbound",
    fromAddress: "+14164687123",
    toAddress: "+14162831047",
    subject: "Moneris Underwriter Call",
    body: "Call from Moneris underwriter Sandra Chen. Duration: 12 minutes. Discussed business model and asked clarifying questions about monthly volume projections. Requested updated bank statement showing recent transaction activity. Seemed satisfied with answers overall.",
    voicemailUrl: null,
    voicemailTranscription: null,
    attachments: [],
    isRead: true,
    isFlagged: false,
    actionNeeded: false,
    actionNotes: null,
    receivedAt: new Date("2026-03-25T11:30:00"),
  },

  // --- Square Communications ---
  {
    type: "email",
    direction: "inbound",
    fromAddress: "noreply@squareup.com",
    toAddress: "contact@freshpresso.ca",
    subject: "Welcome to Square - Account Activated",
    body: "Hi there,\n\nYour Square account has been activated and you are ready to start accepting payments.\n\nHere are your next steps:\n- Download the Square Point of Sale app\n- Set up your product catalog\n- Run a test transaction\n\nYour deposit schedule is set to next-business-day for standard transfers.\n\nWelcome aboard!\nThe Square Team",
    voicemailUrl: null,
    voicemailTranscription: null,
    attachments: [],
    isRead: true,
    isFlagged: false,
    actionNeeded: false,
    actionNotes: null,
    receivedAt: new Date("2026-03-10T16:45:00"),
  },
  {
    type: "email",
    direction: "inbound",
    fromAddress: "security@squareup.com",
    toAddress: "contact@freshpresso.ca",
    subject: "Action Required: Verify Your Identity",
    body: "We noticed some unusual activity on your account and need to verify your identity to continue processing payments.\n\nPlease log in to your Square Dashboard and complete the identity verification process within 48 hours.\n\nIf you do not verify, your account may be temporarily limited.\n\n- Square Security Team",
    voicemailUrl: null,
    voicemailTranscription: null,
    attachments: [],
    isRead: false,
    isFlagged: true,
    actionNeeded: true,
    actionNotes: "URGENT: Identity verification needed within 48 hours to avoid account limitation.",
    receivedAt: new Date("2026-04-01T08:20:00"),
  },

  // --- Helcim Communications ---
  {
    type: "email",
    direction: "inbound",
    fromAddress: "onboarding@helcim.com",
    toAddress: "admin@northerngoods.ca",
    subject: "Your Helcim Application is Approved!",
    body: "Great news!\n\nYour merchant application has been approved. Here are your account details:\n\nMerchant ID: HLC-998271\nInterchange-Plus Rate: Interchange + 0.30% + $0.08/txn\nDeposit Schedule: Next business day\n\nTo get started, log in to your Helcim dashboard and set up your payment page or integrate using our API.\n\nWe are excited to have you on board!\n\nHelcim Onboarding Team",
    voicemailUrl: null,
    voicemailTranscription: null,
    attachments: [{ filename: "Helcim_Welcome_Package.pdf", url: "/uploads/helcim-welcome.pdf", size: 245000 }],
    isRead: true,
    isFlagged: false,
    actionNeeded: false,
    actionNotes: null,
    receivedAt: new Date("2026-03-12T13:00:00"),
  },
  {
    type: "sms",
    direction: "inbound",
    fromAddress: "+18779153570",
    toAddress: "+16479201834",
    subject: null,
    body: "Helcim: Your two-factor authentication code is 592047. Enter this on the login screen. Valid for 5 minutes.",
    voicemailUrl: null,
    voicemailTranscription: null,
    attachments: [],
    isRead: true,
    isFlagged: false,
    actionNeeded: false,
    actionNotes: null,
    receivedAt: new Date("2026-03-14T09:12:00"),
  },

  // --- Stripe Communications ---
  {
    type: "email",
    direction: "inbound",
    fromAddress: "notifications@stripe.com",
    toAddress: "dev@techlauncher.io",
    subject: "Your Stripe account is ready",
    body: "You can now accept payments with Stripe.\n\nYour account has been activated in live mode. Here is what you can do next:\n\n- Create your first payment link\n- Integrate Stripe Checkout on your website\n- Set up subscription billing\n\nYour first payout will be deposited 7 days after your first successful payment.\n\nGet started: https://dashboard.stripe.com\n\nStripe Team",
    voicemailUrl: null,
    voicemailTranscription: null,
    attachments: [],
    isRead: true,
    isFlagged: false,
    actionNeeded: false,
    actionNotes: null,
    receivedAt: new Date("2026-02-28T10:00:00"),
  },
  {
    type: "email",
    direction: "inbound",
    fromAddress: "support@stripe.com",
    toAddress: "dev@techlauncher.io",
    subject: "Account Review - Additional Information Needed",
    body: "We are conducting a routine review of your Stripe account and need additional information to continue processing payments.\n\nPlease provide:\n1. A detailed description of your products/services\n2. Your refund and return policy URL\n3. Customer service contact information displayed on your website\n\nPlease respond within 5 business days. During this review, payouts may be paused.\n\nStripe Risk & Compliance Team",
    voicemailUrl: null,
    voicemailTranscription: null,
    attachments: [],
    isRead: true,
    isFlagged: true,
    actionNeeded: true,
    actionNotes: "Stripe account review. Need to update website with refund policy and respond within 5 days. Payouts are paused.",
    receivedAt: new Date("2026-03-18T15:30:00"),
  },
  {
    type: "sms",
    direction: "inbound",
    fromAddress: "+14156127823",
    toAddress: "+16475638291",
    subject: null,
    body: "Stripe: 638291 is your verification code. Do not share this code. @stripe.com #638291",
    voicemailUrl: null,
    voicemailTranscription: null,
    attachments: [],
    isRead: true,
    isFlagged: false,
    actionNeeded: false,
    actionNotes: null,
    receivedAt: new Date("2026-03-01T11:22:00"),
  },

  // --- PayPal/Braintree Communications ---
  {
    type: "email",
    direction: "inbound",
    fromAddress: "service@paypal.ca",
    toAddress: "orders@canadiancraft.ca",
    subject: "Your PayPal Business Account is Ready",
    body: "Welcome to PayPal Business!\n\nYour account has been set up and you can now accept payments from customers worldwide.\n\nAccount Type: Business\nPayment Methods: PayPal, Debit, Credit Card\nWithdrawal Method: Bank transfer to your linked account\n\nTo enhance your account limits, please complete the business verification process in your account settings.\n\nPayPal Canada",
    voicemailUrl: null,
    voicemailTranscription: null,
    attachments: [],
    isRead: true,
    isFlagged: false,
    actionNeeded: false,
    actionNotes: null,
    receivedAt: new Date("2026-03-05T12:00:00"),
  },
  {
    type: "email",
    direction: "inbound",
    fromAddress: "compliance@paypal.ca",
    toAddress: "orders@canadiancraft.ca",
    subject: "Action Required: Account Limitation Notice",
    body: "We have limited your account due to concerns regarding recent transaction activity.\n\nTo restore full account access, please:\n1. Provide proof of product delivery for recent transactions\n2. Upload a government-issued photo ID\n3. Provide invoices or receipts for disputed charges\n\nYou may still receive payments but withdrawals are restricted until the review is complete.\n\nPayPal Compliance Team",
    voicemailUrl: null,
    voicemailTranscription: null,
    attachments: [],
    isRead: false,
    isFlagged: true,
    actionNeeded: true,
    actionNotes: "PayPal account limited. Need to upload ID and proof of delivery for recent orders. Withdrawals frozen.",
    receivedAt: new Date("2026-04-05T09:45:00"),
  },

  // --- Shopify Payments Communications ---
  {
    type: "email",
    direction: "inbound",
    fromAddress: "noreply@shopify.com",
    toAddress: "hello@trendyboutique.ca",
    subject: "Shopify Payments is now active on your store",
    body: "Congratulations! Shopify Payments has been activated on your store.\n\nYou are now set up to accept Visa, Mastercard, American Express, and Apple Pay directly through your Shopify store.\n\nYour transaction rate: 2.4% + $0.30 CAD (Shopify plan)\nPayout schedule: Business days, 2-day rolling\n\nNo additional gateway fees apply when using Shopify Payments.\n\nHappy selling!\nShopify Team",
    voicemailUrl: null,
    voicemailTranscription: null,
    attachments: [],
    isRead: true,
    isFlagged: false,
    actionNeeded: false,
    actionNotes: null,
    receivedAt: new Date("2026-03-08T14:20:00"),
  },
  {
    type: "sms",
    direction: "inbound",
    fromAddress: "+16136127890",
    toAddress: "+19057124638",
    subject: null,
    body: "Shopify: Your login code is 482917. This code expires in 10 minutes.",
    voicemailUrl: null,
    voicemailTranscription: null,
    attachments: [],
    isRead: true,
    isFlagged: false,
    actionNeeded: false,
    actionNotes: null,
    receivedAt: new Date("2026-03-08T14:05:00"),
  },

  // --- Chase Paymentech Communications ---
  {
    type: "email",
    direction: "inbound",
    fromAddress: "merchantservices@chase.com",
    toAddress: "finance@premiumretail.ca",
    subject: "Application Under Review - Chase Paymentech",
    body: "Dear Applicant,\n\nThank you for your interest in Chase Paymentech merchant services. Your application has been received and assigned to underwriting for review.\n\nApplication Reference: CPT-2026-1192\nExpected Timeline: 10-15 business days\n\nOur team may contact you to request additional documentation including financial statements and business references. Please ensure your contact information is current.\n\nChase Paymentech Canada",
    voicemailUrl: null,
    voicemailTranscription: null,
    attachments: [],
    isRead: true,
    isFlagged: false,
    actionNeeded: false,
    actionNotes: null,
    receivedAt: new Date("2026-03-02T10:30:00"),
  },
  {
    type: "call",
    direction: "inbound",
    fromAddress: "+14167891234",
    toAddress: "+14163947582",
    subject: "Chase Paymentech - Financial Review",
    body: "Voicemail from Chase Paymentech underwriting. The caller identified himself as James Park, Senior Underwriter. He requested a callback regarding the financial review for application CPT-2026-1192. Mentioned they need 2 years of financial statements and a bank comfort letter. Callback number: 416-789-1234 ext 4521.",
    voicemailUrl: "/uploads/voicemail/chase-20260310.mp3",
    voicemailTranscription: "Hi, this is James Park calling from Chase Paymentech underwriting. I am reviewing application CPT-2026-1192 and need to discuss your financial documentation. We will need two years of audited financial statements and a bank comfort letter. Please call me back at your earliest convenience at 416-789-1234 extension 4521. Thank you.",
    attachments: [],
    isRead: true,
    isFlagged: true,
    actionNeeded: true,
    actionNotes: "Callback needed to Chase underwriter James Park. Prepare 2-year financial statements and request bank comfort letter from TD.",
    receivedAt: new Date("2026-03-10T16:15:00"),
  },
  {
    type: "email",
    direction: "inbound",
    fromAddress: "merchantservices@chase.com",
    toAddress: "finance@premiumretail.ca",
    subject: "Application Denied - CPT-2026-1192",
    body: "Dear Applicant,\n\nAfter careful review, we are unable to approve your merchant services application CPT-2026-1192 at this time.\n\nReason: Insufficient business operating history. Our requirements specify a minimum of 2 years of verifiable business trading history for the requested monthly volume.\n\nYou may reapply after 6 months or when your business has established a longer operating history.\n\nChase Paymentech Underwriting",
    voicemailUrl: null,
    voicemailTranscription: null,
    attachments: [],
    isRead: true,
    isFlagged: true,
    actionNeeded: false,
    actionNotes: "Application denied due to insufficient operating history. Can reapply in 6 months. Consider Nuvei or Helcim as alternatives.",
    receivedAt: new Date("2026-03-28T11:00:00"),
  },

  // --- TD Merchant Solutions Communications ---
  {
    type: "email",
    direction: "inbound",
    fromAddress: "merchant.services@td.com",
    toAddress: "accounting@torontodining.ca",
    subject: "TD Merchant Solutions - Application Confirmation",
    body: "Dear Valued Customer,\n\nWe have received your application for TD Merchant Solutions. As a TD business banking customer, your application will receive expedited processing.\n\nApplication ID: TDM-2026-7734\nEstimated Processing Time: 5-7 business days\n\nYour branch manager, Patricia Wong, has endorsed your application which may help streamline the approval process.\n\nTD Merchant Solutions Team",
    voicemailUrl: null,
    voicemailTranscription: null,
    attachments: [],
    isRead: true,
    isFlagged: false,
    actionNeeded: false,
    actionNotes: null,
    receivedAt: new Date("2026-03-14T09:00:00"),
  },
  {
    type: "email",
    direction: "inbound",
    fromAddress: "merchant.services@td.com",
    toAddress: "accounting@torontodining.ca",
    subject: "Congratulations - TD Merchant Account Approved",
    body: "Dear Merchant,\n\nWe are pleased to inform you that your TD Merchant Solutions application TDM-2026-7734 has been approved.\n\nMerchant ID: TDM-9982714\nMonthly Volume Approved: $75,000\nRate: Interchange + 0.35% + $0.10/txn\nMonthly Fee: $14.95\nEquipment: Clover Flex terminal (shipped separately)\n\nYour account will be fully active within 2 business days. Equipment delivery takes 3-5 business days.\n\nWelcome to TD Merchant Solutions!",
    voicemailUrl: null,
    voicemailTranscription: null,
    attachments: [{ filename: "TD_Merchant_Agreement.pdf", url: "/uploads/td-agreement.pdf", size: 340000 }],
    isRead: true,
    isFlagged: false,
    actionNeeded: false,
    actionNotes: null,
    receivedAt: new Date("2026-03-21T10:30:00"),
  },

  // --- Global Payments Communications ---
  {
    type: "email",
    direction: "inbound",
    fromAddress: "onboarding@globalpayments.com",
    toAddress: "ops@nationwidservices.ca",
    subject: "Merchant Application Received - Global Payments",
    body: "Dear Applicant,\n\nYour merchant application has been received and is being reviewed by our underwriting team.\n\nReference Number: GP-CA-2026-38291\nExpected Review Time: 5-10 business days\n\nPlease ensure all documentation has been submitted through our secure portal. Incomplete applications may experience delays.\n\nGlobal Payments Canada",
    voicemailUrl: null,
    voicemailTranscription: null,
    attachments: [],
    isRead: true,
    isFlagged: false,
    actionNeeded: false,
    actionNotes: null,
    receivedAt: new Date("2026-03-16T11:15:00"),
  },
  {
    type: "call",
    direction: "inbound",
    fromAddress: "+19054821390",
    toAddress: "+19053821947",
    subject: "Global Payments - Site Verification",
    body: "Call from Global Payments field representative David Morrison. He called to schedule a site inspection of the business location as part of the underwriting process for application GP-CA-2026-38291. Inspection scheduled for March 25, 2026 at 2:00 PM. Applicant needs to have business license, incorporation documents, and POS setup area ready for inspection.",
    voicemailUrl: null,
    voicemailTranscription: null,
    attachments: [],
    isRead: true,
    isFlagged: true,
    actionNeeded: true,
    actionNotes: "Site inspection scheduled for March 25 at 2:00 PM. Prepare business license and incorporation docs for inspector.",
    receivedAt: new Date("2026-03-19T15:45:00"),
  },

  // --- Paysafe/Nuvei Communications ---
  {
    type: "email",
    direction: "inbound",
    fromAddress: "merchant.onboarding@nuvei.com",
    toAddress: "support@digitalvault.io",
    subject: "Nuvei - Application in Progress",
    body: "Dear Merchant,\n\nYour application for payment processing services with Nuvei has been received and is under review.\n\nApplication Reference: NUV-2026-CA-4821\nAssigned Specialist: Marie-Claire Dubois\n\nAs your business falls into a specialized vertical, our enhanced due diligence process may require additional documentation:\n- 6 months of processing statements from your current processor\n- Detailed refund/chargeback policy\n- Privacy policy and terms of service URLs\n\nMarie-Claire will be in touch within 2-3 business days.\n\nNuvei Onboarding Team",
    voicemailUrl: null,
    voicemailTranscription: null,
    attachments: [],
    isRead: true,
    isFlagged: false,
    actionNeeded: true,
    actionNotes: "Prepare processing statements and ensure website has refund policy, privacy policy, and TOS pages live.",
    receivedAt: new Date("2026-03-11T13:30:00"),
  },
  {
    type: "email",
    direction: "inbound",
    fromAddress: "marie-claire.dubois@nuvei.com",
    toAddress: "support@digitalvault.io",
    subject: "Re: NUV-2026-CA-4821 - Approved with Conditions",
    body: "Bonjour,\n\nI am pleased to inform you that your application NUV-2026-CA-4821 has been approved with the following conditions:\n\n- Monthly processing cap: $150,000 CAD (reviewable after 3 months)\n- Rolling reserve: 5% held for 180 days\n- Chargeback threshold: 1% (account review triggered if exceeded)\n- MCC assigned: 5816 (Digital Goods)\n\nPlease review and sign the attached merchant agreement. Once signed, integration can begin immediately.\n\nCordialement,\nMarie-Claire Dubois\nMerchant Success Specialist, Nuvei",
    voicemailUrl: null,
    voicemailTranscription: null,
    attachments: [
      { filename: "Nuvei_Merchant_Agreement.pdf", url: "/uploads/nuvei-agreement.pdf", size: 520000 },
      { filename: "Nuvei_API_Integration_Guide.pdf", url: "/uploads/nuvei-api-guide.pdf", size: 180000 },
    ],
    isRead: true,
    isFlagged: true,
    actionNeeded: true,
    actionNotes: "Review and sign merchant agreement. Note: 5% rolling reserve for 180 days. Monthly cap $150K.",
    receivedAt: new Date("2026-03-17T16:00:00"),
  },
  {
    type: "sms",
    direction: "inbound",
    fromAddress: "+15149284710",
    toAddress: "+15148273610",
    subject: null,
    body: "Nuvei: Votre code de verification est 371829. Ce code expire dans 10 minutes. Ne partagez pas ce code.",
    voicemailUrl: null,
    voicemailTranscription: null,
    attachments: [],
    isRead: true,
    isFlagged: false,
    actionNeeded: false,
    actionNotes: null,
    receivedAt: new Date("2026-03-17T15:55:00"),
  },

  // --- Fiserv/Clover Communications ---
  {
    type: "email",
    direction: "inbound",
    fromAddress: "support@clover.com",
    toAddress: "manager@oakvillecafe.ca",
    subject: "Clover Account Setup Confirmation",
    body: "Welcome to Clover!\n\nYour Clover merchant account has been approved and your POS equipment is being prepared for shipment.\n\nMerchant ID: CLV-4829103\nEquipment Ordered: Clover Station Duo\nEstimated Delivery: March 28-30, 2026\n\nOnce you receive your equipment, follow the setup guide included in the box. Our support team is available 24/7 at 1-888-552-5683.\n\nClover by Fiserv",
    voicemailUrl: null,
    voicemailTranscription: null,
    attachments: [{ filename: "Clover_QuickStart_Guide.pdf", url: "/uploads/clover-quickstart.pdf", size: 890000 }],
    isRead: true,
    isFlagged: false,
    actionNeeded: false,
    actionNotes: null,
    receivedAt: new Date("2026-03-24T10:00:00"),
  },
  {
    type: "sms",
    direction: "inbound",
    fromAddress: "+18885525683",
    toAddress: "+19053821947",
    subject: null,
    body: "Clover: Your equipment shipment CLV-SHP-48291 is out for delivery today. Expected between 10 AM - 4 PM. Track: https://track.clover.com/s/48291",
    voicemailUrl: null,
    voicemailTranscription: null,
    attachments: [],
    isRead: true,
    isFlagged: false,
    actionNeeded: false,
    actionNotes: null,
    receivedAt: new Date("2026-03-29T08:30:00"),
  },

  // --- Elavon Communications ---
  {
    type: "email",
    direction: "inbound",
    fromAddress: "merchantapplications@elavon.com",
    toAddress: "billing@healthplusmedical.ca",
    subject: "Elavon Merchant Application - Documents Required",
    body: "Dear Applicant,\n\nThank you for your application for Elavon merchant services. To continue processing your application, we require the following:\n\n1. Completed PCI-DSS Self-Assessment Questionnaire (SAQ-A or SAQ-D)\n2. Signed Merchant Processing Agreement (attached)\n3. Bank reference letter from your financial institution\n4. Copy of professional/medical license\n\nPlease submit these documents within 15 business days to avoid application expiry.\n\nElavon Canada Merchant Services",
    voicemailUrl: null,
    voicemailTranscription: null,
    attachments: [
      { filename: "Elavon_Merchant_Agreement.pdf", url: "/uploads/elavon-agreement.pdf", size: 420000 },
      { filename: "PCI_SAQ_A_Template.pdf", url: "/uploads/pci-saq-a.pdf", size: 150000 },
    ],
    isRead: true,
    isFlagged: true,
    actionNeeded: true,
    actionNotes: "Need to complete PCI-DSS SAQ, sign agreement, obtain bank reference letter, and provide medical license copy. 15-day deadline.",
    receivedAt: new Date("2026-03-07T14:00:00"),
  },
  {
    type: "call",
    direction: "inbound",
    fromAddress: "+18004567890",
    toAddress: "+16048372914",
    subject: "Elavon - Account Manager Introduction",
    body: "Introductory call from Elavon account manager Rachel Kim. She is the assigned account manager for the healthcare vertical. Discussed optimal terminal configuration for medical office (chip + tap preferred). Offered to schedule a training session once the account is activated. Mentioned a promotional rate of interchange + 0.25% for the first 6 months for healthcare merchants.",
    voicemailUrl: null,
    voicemailTranscription: null,
    attachments: [],
    isRead: true,
    isFlagged: false,
    actionNeeded: false,
    actionNotes: null,
    receivedAt: new Date("2026-03-09T11:00:00"),
  },

  // --- General / Cross-Processor Communications ---
  {
    type: "email",
    direction: "outbound",
    fromAddress: "admin@midfactory.com",
    toAddress: "underwriting@moneris.com",
    subject: "Re: Additional Documents Required - MON-2026-04891",
    body: "Dear Moneris Underwriting,\n\nPlease find attached the requested documentation:\n1. Business bank statements (Jan-Mar 2026)\n2. Provincial business license\n3. Commercial lease agreement as proof of address\n\nPlease let us know if you require anything else.\n\nBest regards",
    voicemailUrl: null,
    voicemailTranscription: null,
    attachments: [
      { filename: "Bank_Statements_Q1_2026.pdf", url: "/uploads/bank-statements-q1.pdf", size: 1200000 },
      { filename: "Business_License_ON.pdf", url: "/uploads/business-license.pdf", size: 350000 },
      { filename: "Commercial_Lease.pdf", url: "/uploads/commercial-lease.pdf", size: 890000 },
    ],
    isRead: true,
    isFlagged: false,
    actionNeeded: false,
    actionNotes: null,
    receivedAt: new Date("2026-03-22T16:30:00"),
  },
  {
    type: "sms",
    direction: "outbound",
    fromAddress: "+14162831047",
    toAddress: "+14164687123",
    subject: null,
    body: "Hi Sandra, this is regarding Moneris application MON-2026-04891. I have uploaded the requested bank statements to the portal. Please confirm receipt. Thank you.",
    voicemailUrl: null,
    voicemailTranscription: null,
    attachments: [],
    isRead: true,
    isFlagged: false,
    actionNeeded: false,
    actionNotes: null,
    receivedAt: new Date("2026-03-22T16:35:00"),
  },
  {
    type: "email",
    direction: "inbound",
    fromAddress: "noreply@stripe.com",
    toAddress: "dev@techlauncher.io",
    subject: "Payout of $3,247.82 CAD is on its way",
    body: "A payout of $3,247.82 CAD has been initiated to your bank account ending in 4829.\n\nEstimated arrival: March 20, 2026\nPayout ID: po_1N8xK2...\n\nView details in your Stripe Dashboard.\n\n- Stripe",
    voicemailUrl: null,
    voicemailTranscription: null,
    attachments: [],
    isRead: true,
    isFlagged: false,
    actionNeeded: false,
    actionNotes: null,
    receivedAt: new Date("2026-03-18T06:00:00"),
  },
  {
    type: "email",
    direction: "inbound",
    fromAddress: "alerts@helcim.com",
    toAddress: "admin@northerngoods.ca",
    subject: "Chargeback Notification - Case #CB-9912",
    body: "A chargeback has been filed against your merchant account.\n\nCase Number: CB-9912\nAmount: $189.99 CAD\nReason Code: 10.4 (Other Fraud - Card Absent Environment)\nDeadline for Response: April 5, 2026\n\nTo respond to this chargeback, log in to your Helcim dashboard and upload supporting documentation (proof of delivery, customer communication, etc.).\n\nFailure to respond by the deadline will result in the chargeback being automatically resolved in favor of the cardholder.\n\nHelcim Dispute Resolution Team",
    voicemailUrl: null,
    voicemailTranscription: null,
    attachments: [],
    isRead: false,
    isFlagged: true,
    actionNeeded: true,
    actionNotes: "URGENT: Chargeback response needed by April 5. Gather proof of delivery and customer correspondence for case CB-9912.",
    receivedAt: new Date("2026-03-26T09:00:00"),
  },
  {
    type: "email",
    direction: "inbound",
    fromAddress: "renewals@moneris.com",
    toAddress: "info@maplecommerce.ca",
    subject: "Annual PCI Compliance Renewal Reminder",
    body: "Dear Merchant,\n\nYour annual PCI-DSS compliance validation is due within the next 30 days.\n\nPlease complete your Self-Assessment Questionnaire (SAQ) through our compliance portal at https://compliance.moneris.com\n\nNon-compliance may result in a monthly non-compliance fee of $29.95.\n\nMoneris Compliance Team",
    voicemailUrl: null,
    voicemailTranscription: null,
    attachments: [],
    isRead: false,
    isFlagged: false,
    actionNeeded: true,
    actionNotes: "PCI compliance renewal due within 30 days. Complete SAQ on Moneris portal to avoid $29.95/month fee.",
    receivedAt: new Date("2026-04-02T08:00:00"),
  },
];
